<?php  $scrpt_vrsn_dt  = 'advisory_c_small.php|01|2023-02-23|';  # empty DS-txt + dew + new file kindex | release 2012_lts
#-----------------------------------------------
#         PWS-Dashboard - Updates and support by 
#     Wim van der Kuil https://pwsdashboard.com/
#-----------------------------------------------
#       display source of script if requested so
#-----------------------------------------------
if (isset($_REQUEST['sce']) && strtolower($_REQUEST['sce']) == 'view' ) {
   $filenameReal = __FILE__;    #               display source of script if requested so
   $download_size = filesize($filenameReal);
   header('Pragma: public');
   header('Cache-Control: private');
   header('Cache-Control: no-cache, must-revalidate');
   header("Content-type: text/plain");
   header("Accept-Ranges: bytes");
   header("Content-Length: $download_size");
   header('Connection: close');
   readfile($filenameReal);
   exit;}
elseif (!isset ($_REQUEST['test'])) 
     {  ini_set('display_errors', 0);   error_reporting(0);}
header('Content-type: text/html; charset=UTF-8');  #### 2021-02-19
# -------------------save list of loaded scrips;
if (!isset ($stck_lst) ) {$stck_lst = '';}
$stck_lst      .= basename(__FILE__).' ('.__LINE__.') version =>'.$scrpt_vrsn_dt.PHP_EOL;       
#
# ------------check if script is already running
$string = str_replace('.php','',basename(__FILE__));
if (isset ($$string) ) {echo 'Advisory_c_small is already displayed'; return;}
$$string = $string;
#
# -------------load weatherdata and all settings 
$scrpt          = 'PWS_livedata.php'; 
$stck_lst      .= basename(__FILE__).' ('.__LINE__.') include_once =>'.$scrpt.PHP_EOL;
include_once $scrpt; 
#
# ------------------------- translation of texts
$lng_lightn1    = lang('Lightning Strike Nearby');
$lng_lightn2    = lang('Possible Storm Approaching');
$lng_freeze1    = lang('Caution');  // +  firerisk
$lng_freeze2    = lang('Dewpoint');
$lng_freeze3    = lang('Below Freezing');
$lng_fire1      = lang('Firerisk');
$lng_fire2      = lang('Possible');
$lng_aurora1    = lang('Aurora');
$lng_aurora2    = lang('Viewing Possible');
$lng_aurora3    = lang('Radio Aurora Possible');
$lng_snow1      = lang('Expect'); 
$lng_snow2      = lang('Snow').' '.lang('Showers');
$lng_snow3      = lang('This Week');
$lng_snow4      = lang('Rain').' '.lang('Showers');
$lng_thun3      = lang('(Severe) thunderstorms possible');
$no_advisory    = lang('Have a nice day');
#
# --- extra settings  TODO  move to settings file?? 
#
$dist_lightning = 50;   // max distance of lightning advisory
$age_lightning  = 600;  // max age
$show_freeze    = true; // set to false if no freezing messages are wanted
$show_aurora    = true; // set to false if you do not want aurora messages
$aurora_kp      = 6;    // minimum kp before showing message http://www.aurora-service.eu/aurora-school/all-about-the-kp-index/
#
# ----------------   housekeeping   convert to C
$tmp    = $weather['temp'];   
$dew    = $weather['dewpoint']; 
if ($tempunit <> 'C') 
     {  $tmp     =  round (5*($tmp -32)/9); 
        $dew     =  round (5*($dew -32)/9);}   # 2023-02-15
#
if ($tmp < -5)        { $show_freeze = false;}  // to remove to much freeze messages
if ((int) $lat < 52 ) { $show_aurora = false;}  // usable in northern countries only
#
# ------------------ style of enclosing html box
$box_style      = 'width: 55px; height: 55px; float: left; margin: 2px; padding: 2px; padding-top: 10px; border-right-width: 1px;';
#
#-----------------------------------------------
# now all possible situations for a message are checked
#-----------------------------------------------
#
#        weatheralarms are generated by external scripts
$return = false; 
if (isset ($weatheralarm) && $weatheralarm == 'europe') 
     {  $return = include 'wrnWarningEU.php';}
elseif (isset ($weatheralarm) && $weatheralarm == 'curly') 
     {  $return = include 'wrnWarningCURLY.php';}
elseif (isset ($weatheralarm) && $weatheralarm == 'canada') 
     {  $return = include 'wrnWarningEC.php';}
elseif (isset ($weatheralarm) && $weatheralarm == 'au') 
     {  $return = include 'wrnWarningAU.php';}
elseif (isset ($weatheralarm) && $weatheralarm == 'uk') 
     {  $return = include 'wrnWarningUK.php';}
if ($return === true)
     {  echo $wrnStrings;
        if (isset ($_REQUEST['test']) ) { echo '<!-- '.PHP_EOL.$stck_lst.'-->'.PHP_EOL; $stck_lst='';}
        return;}  
#     
# ---------------------------------   lightning
# Can be from boltek sensor or WeatherFlow sensor
# For Boltek
#  ==>  we have to load the script for those values
#
if (isset ($boltek) && $boltek == true)
     {  $boltek_values  = true;
        $scrpt          = 'lightning_boltek_small.php'; 
        $stck_lst      .= basename(__FILE__).' ('.__LINE__.') include_once =>'.$scrpt.PHP_EOL;
        include_once $scrpt;}

# For WeatherFlow the lightning values are loaded by default
#
# Now we can check if there is recent lightning not to far away
#
if (isset ($weather['lightningtimeago'])) {$lght = (int)$weather['lightningtimeago'];}  else {$lght = -1;}
if (isset ($weather['lightningkm']))      {$dist = (int)$weather['lightningkm'];     }  else {$dist = 9999999;}
if (    $lght > 0 && $lght < $age_lightning && $dist < $dist_lightning)
    {   if ($distanceunit == 'km')
             {  $distance       = number_format($weather['lightningkm'],0,'.','');}
        else {  $distance       = number_format($weather['lightningmi'],0,'.','');} 
        $unit   = lang ($distanceunit);  
        $return = '<div class= "PWS_div_left PWS_round" style="'.$box_style.'">
     <span class="orange" style="font-size: 14px;">'.$distance.'</span><br />'.$unit.'
</div> 
<div style="font-size:12px; padding-top: 10px;">
<span class="orange">'.$lightningsvg.'</span> '.$lng_lightn1.'<br />'.$lng_lightn2.'</div>
</div>'.PHP_EOL;}     
#
#  ------------------------------------ freezing 
elseif ($show_freeze && $tmp <= 0 && $dew <= 0)
     {  $return = '<div class= "PWS_div_left PWS_round" style="'.$box_style.' padding-top: 16px;">
    <span class="blue" style="font-size: 14px;">'.number_format($weather["dewpoint"],1).'&deg;</span>
 </div>
<div style="font-size:12px; padding-top: 10px;">
<span class="orange">'.$lng_freeze1.'</span> '.$lng_freeze2.'<br />'.$lng_freeze3.'</div>
</div>'.PHP_EOL; } 
#
#-------------------------------------  fire risk
elseif ($weather["humidity"] <= 40 && $tmp >= 27)
     {  $return = '<div class= "PWS_div_left" style="'.$box_style.'">
    <span class="maroon" style="font-size: 12px;">'.number_format($weather["temp"],1).'</span>&deg;'.$tempunit.'
    <span class="maroon" style="font-size: 12px;">'.number_format($weather["humidity"],0).'</span>%
 </div>
<div style="font-size:12px; padding-top: 10px;">
<span class="orange">'.$lng_freeze1.'</span><br />'.$lng_fire1.' '.$lng_fire2.'</div>
</div>'.PHP_EOL; }
#
#------------------- optional aurora messages (kp index)
if ($return === false && $show_aurora == true)     
     {  $kp = 0;
        if (file_exists ($fl_folder.$kndx_fl) ) 
             {  $str    = file_get_contents($fl_folder.$kndx_fl); 
                $arr    = json_decode($str,true); #echo __LINE__.print_r($arr,true); exit;
                if ($arr <> NULL && $arr <> false && count ($arr) > 0)  
                     {  $last  = count ($arr) - 1;
                        if ( array_key_exists ('kp_index', $arr[$last]) )
                             {  $kp     =  $arr[$last]['kp_index']; }
                        } // check last item in json array
                } // eo file exists 
$multiply = 1;         # $multiply = 10; # for test
$kp = $kp*$multiply;   # for test
        if ($kp >= $aurora_kp) # aurora
             {  $return = '<div class= "PWS_div_left" style="'.$box_style.'">
    <span class="maroon" style="font-size: 16px;">'.number_format($kp,1).'</span><br /> kp
 </div>
<div style="font-size:12px; padding-top: 10px;">
<span class="orange">'.$lng_aurora1.'</span> '.$lng_aurora2
.'<br />144 MHz '.$lng_aurora3.'
</div>'.PHP_EOL;} // eo kp >= 5
        }  // eo aurora
# ----------------------------------------------
#          Generate forecast message to be shown
# 
# ---------------------------   Darksky forecast
if ($return === false && $fct_darksky_block_used == true) #### 2020-10-14// DarkSky check forecast , rain , snow 
     {  $scrpt          = 'fct_darksky_shared.php'; 
        $stck_lst      .= basename(__FILE__).' ('.__LINE__.') include_once =>'.$scrpt.PHP_EOL;
        include_once $scrpt;
        echo '<!-- $darkskydayIcon='.$darkskydayIcon.' -->'.PHP_EOL;
#
        if (isset ($darkskyTodaySummary) &&  $darkskyTodaySummary <> '')        # 2023-02-23 
             {  if (strlen($darkskyTodaySummary) < 90) {$extra='<br />';} else {$extra='';}
                $return =  '<div style="padding: 4px;">'.$extra.$darkskyTodaySummary.'</div>'.PHP_EOL; } 
#
# ------------------    Darksky alerts rain,snow  
        elseif (isset ($darkskydayIcon) && strpos (' '.$darkskydayIcon,'snow'))
             {  $return = '<div style="padding: 8px;">'
                        .$lng_snow1
                        .' <span class="blue">'.$lng_snow2.'</span><br />'
                        .$lng_snow3.'</div>'.PHP_EOL;}
#       
        elseif (isset ($darkskydayIcon)  && strpos (' '.$darkskydayIcon,'rain'))
             {  $return =  '<div style="padding: 8px;">'
                        .$lng_snow1
                        .' <span class="blue">'.$lng_snow4.'</span><br />'
                        .$lng_snow3.'</div>'.PHP_EOL;}
        } // eo darksky
#
#---------------------------- WeatherUnderground
if ($return === false && $fct_wu_block_used == true)  #### 2020-10-14
     {  $file           = $fl_folder.'wufct_'.$locale_wu.'_'.$wu_fct_unit.'.txt';  
        $json           = file_get_contents($file); 
        $response       = json_decode($json, true); # echo '<pre>response["daypart"]= '.print_r($response['daypart'], true) ; exit;     
        if ($response['daypart'][0]['dayOrNight'][0] == '') {$n = 1;} else {$n=0;}
        $thun           = (int) $response['daypart'][0]['thunderIndex'][$n];
        $uv             = (int) $response['daypart'][0]['uvIndex'][$n];
        $uv_text        = (string) $response['daypart'][0]['uvDescription'][$n];
        if ($thun > 3)
             {  $return =  '<div style="padding: 4px;">'.$lng_thun3.'</div>'.PHP_EOL;  }
        elseif ($uv > 9) 
             {  if ($uv > 10) {$color = 'color: red;'; } 
                $return =  '<div style="padding: 4px; '.$color.'"><br />'.lang('UV').' '.$uv .' '.lang('forecast').'<br />'.lang('Reduce Sun Exposure').'</div>'.PHP_EOL;  }
        else {  $string = $response['daypart'][0]['narrative'][$n];
                if (strlen ($string) > 100) 
                     {  $string =  '<div style="padding: 4px; font-size: 10px; line-height: 11px; height: 60px; overflow-Y: auto;">'.$string.'</div>'.PHP_EOL; }
                else {  $string =  '<div style="padding: 4px;">'.$string.'</div>'.PHP_EOL; }
                $return = $string;}
        } // eo WU
#
#------------------------------------------ WXSIM
if ($return === false && $fct_wxsim_block_used == true)  #### 2020-10-14
     {  $scrpt          = 'fct_wxsim_shared.php'; 
        $stck_lst      .= basename(__FILE__).' ('.__LINE__.') include_once =>'.$scrpt.PHP_EOL;
        include_once $scrpt;
        if (isset ($arr_pp) && count ($arr_pp) > 0)
             {  $arr    = $arr_pp[0];
                $from   = array ('<br />','<br/>','<br>');
                $text   = str_replace ($from,' ',$arr['text']);
                if (strlen($text) < 90) {$extra='<br />';} else {$extra=' ';}
                if ($arr['tphl'] <> 'blue') {$color = "#FF7C39"; } else {$color = "#01A4B4"; }               
                $string = '<span style="color: '.$color.'">'.$arr['part'].'</span>'.$extra.$text;
                if (strlen ($string) > 100) 
                     {  $return =  '<div style="padding: 4px; font-size: 10px; line-height: 11px; height: 60px; overflow-Y: auto;">'.$string.'</div>'.PHP_EOL; }
                else {  $return =  '<div style="padding: 4px;">'.$string.'</div>'.PHP_EOL; }
                }
        } // eo wxsim
#
#----------------------------------- EC forecast
if ($return === false && $fct_ec_block_used == true) #### 2020-10-14
     {  $EC_area	= $alarm_area;
        $fct_h_needed   = true;
        #
        $scrpt          = 'fct_ec_shared.php'; 
        $stck_lst      .= basename(__FILE__).' ('.__LINE__.') include_once =>'.$scrpt.PHP_EOL;
        include_once $scrpt;
        if (isset ($fcts_arr) && count ($fcts_arr) > 0)
             {  $string = $fcts_arr[0]['text'];
                if (strlen ($string) > 140) 
                     {  $return =  '<div style="padding: 4px; font-size: 10px; line-height: 11px; height: 60px; overflow-Y: auto;">'.$string.'</div>'.PHP_EOL; }
                else {  $return =  '<div style="padding: 4px;">'.$string.'</div>'.PHP_EOL; }
                }
        } // eo Environement canada
#
# --------------------------- no other advisorys
if ($return == false)   // standard message
     {  $return =  '<br />'.$no_advisory.PHP_EOL; }
#
echo $return;
if (isset ($_REQUEST['test']) ) { echo '<!-- '.PHP_EOL.$stck_lst.'-->'.PHP_EOL; $stck_lst='';}
