<?php $scrpt_vrsn_dt  = 'ccn_ec_block.php|01|2021-05-25|';  # check file | release 2012_lts
#-----------------------------------------------
# currentconditionsEC_block
# |-> PWS_livedata.php
# |-> fct_ec_shared.php => loads the needed parts from the EC-xml
# |-> if the icon and condition text are not available 
#     from another script those fields are used from ccn array
# |-> The hourly forecasts are read until the next-hour forecast
#     |-> alll hourly fields are saved
# |-> ccn_shared.php    to print all info
#-----------------------------------------------
#         PWS-Dashboard - Updates and support by 
#     Wim van der Kuil https://pwsdashboard.com/
#-----------------------------------------------
#       display source of script if requested so
#-----------------------------------------------
if (isset($_REQUEST['sce']) && strtolower($_REQUEST['sce']) == 'view' ) {
   $filenameReal = __FILE__;  
   $download_size = filesize($filenameReal);
   header('Pragma: public');
   header('Cache-Control: private');
   header('Cache-Control: no-cache, must-revalidate');
   header('Content-type: text/plain; charset=UTF-8');
   header('Accept-Ranges: bytes');
   header("Content-Length: $download_size");
   header('Connection: close');
   readfile($filenameReal);
   exit;}
elseif (!isset ($_REQUEST['test'])) 
     {  ini_set('display_errors', 0);   error_reporting(0);}
# -------------------save list of loaded scrips;
if (!isset ($stck_lst) ) {$stck_lst = '';}
$stck_lst      .= basename(__FILE__).' ('.__LINE__.') version =>'.$scrpt_vrsn_dt.PHP_EOL;       
#
# ------------check if script is already running
$string = str_replace('.php','',basename(__FILE__));
if (isset ($$string) ) {echo 'This info is already displayed'; return;}
$$string = $string;
#
# -------------load weatherdata and all settings 
$scrpt          = 'PWS_livedata.php'; 
$stck_lst      .= basename(__FILE__).' ('.__LINE__.') include_once =>'.$scrpt.PHP_EOL;
include_once $scrpt; 
#
# -----------------------   load general EC code
$ccn_needed     = true; //  for icon / text
$fct_h_needed   = true; //  for 1 hour description below the icon/text
$EC_area	= $alarm_area;
#
if (!isset ($ccn_arr) ) 
     {  $scrpt          = 'fct_ec_shared.php';    // load genral EC scripts
        $stck_lst      .= basename(__FILE__).' ('.__LINE__.') include_once =>'.$scrpt.PHP_EOL;
        $return         = include_once $scrpt; 
        if ($return == false) 
             {  echo $ec_error; 
                return false;}  #  echo '<pre>'.print_r($ccn_arr,true); exit;
} // eo load util
#-----------------------------------------------
#  save condition icon and texts for current conditions block
# first generate the icon and conditions text
if (!isset ($timeXX) )  // if not already generated by another script
     {  $timeXX = $EC_filetime; // generate condition icon and texts
        $textXX = lang($ccn_arr['condtext']); 
        $stck_lst      .= basename(__FILE__).' ('.__LINE__.') conditions from provider $textXX='.$textXX.PHP_EOL;
        $key    = (int)$ccn_arr['condicon'];  
        $iconXX =  EC_icon ($key);
        $stck_lst      .= basename(__FILE__).' ('.__LINE__.') icon from provider $key='.$key.' $iconXX='.$iconXX.PHP_EOL;
        #
        if (isset ($ccn_small) ) { return;}
        } // eo if not already generated by another script
#
# --------------   find current hour or use last
#   and generate other values for ccn-weatherbox 
$now    = gmdate('Ymdhi',time());               ## test if gmdate is correct
foreach ($dtls_arr as $cond) 
     {  if ($cond['time'] > $now)  { break;} } #echo '<pre>'.print_r($cond,true); exit;
$stck_lst      .= basename(__FILE__).' ('.__LINE__.') used hour ='.$cond['time'].' '.$now.PHP_EOL;
#
$hourlySummary          = $cond['condtext'];
$hourlyTemp             = convert_temp ($cond['temperature'],'C',$tempunit,0); 
$tempC                  = $cond['temperature'];
$hourlychill            = convert_temp ($cond['chill'],'C',$tempunit,0); 
$chillC                 = $cond['chill'];
$hourlyhudx             = convert_temp ($cond['humidex'],'C',$tempunit,0);   
$hudxC                  = $cond['humidex'];     
$hourlyWinddir          = $cond['winddir'];
$hourlyPrecipProb       = $cond['lop'];
$hourlyPrecipType       = '';
$haystack       = strtolower($hourlySummary);
if (ECfound($haystack, 'snow') || ECfound($haystack, 'neige') )
     {  $hourlyPrecipType = 'snow';}
$hourlyprecipIntensity  = 0;
$hourlyWindSpeed        = convert_speed ($cond['windspeed'],$cond['windunit'],$windunit,0) ;
$hourlyWindGust         = convert_speed ($cond['windgust'], $cond['windunit'],$windunit,0) ;
$hourlyUV               = false;
#
#-----------------------------------------------
# After all current condition fields are ready
# we use another general script to print them   
$scrpt          = 'ccn_shared.php';
$stck_lst      .= basename(__FILE__).' ('.__LINE__.') include_once  =>'.$scrpt.PHP_EOL; 
include_once $scrpt;
#
if (isset ($_REQUEST['test']) ) { echo '<!-- '.PHP_EOL.$stck_lst.'-->'.PHP_EOL; $stck_lst='';}
